# argo-app-socialdevs-frontend.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: socialdevs-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/vhgalvez/socialdevs-gitops
    targetRevision: HEAD          # o “main”
    path: apps/socialdevs-frontend
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true