apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: socialdevs-frontend
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: frontend
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://github.com/vhgalvez/socialdevs-gitops'
    targetRevision: main
    path: apps/frontend
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true