apiVersion: apps/v1
kind: Deployment
metadata:
  name: socialdevs-frontend
  labels:
    app: socialdevs-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socialdevs-frontend
  template:
    metadata:
      labels:
        app: socialdevs-frontend
    spec:
      containers:
        - name: frontend
          image: vhgalvez/socialdevs-public-frontend:v1.0.0
          ports:
            - containerPort: 80
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"