apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: socialdevs-ingress
  namespace: socialdevs
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: frontend.socialdevs.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: socialdevs-service
                port:
                  number: 80
