# apps\socialdevs-frontend\kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - ingressroute-public.yaml
  # - ingressroute-local.yaml   # descomenta si también aplicas el entorno local