# apps/socialdevs-frontend/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - socialdevs-frontend-ingressroute-public.yaml
  # - socialdevs-frontend-ingressroute-local.yaml  # ← solo si lo usas en local